# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: Terraform

stages:
  - stage: "terraform apply"
    jobs:
    - job: InstallTerraform
      pool:
        vmImage: ubuntu-latest

      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
        displayName: 'Install terraform'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'aws'
          command: 'init'

      - bash: |
          echo Add other tasks to build, test, and deploy your project.
          echo let us see some magic: $MY_MAPPED_ENV_VAR
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
        env:
          MY_MAPPED_ENV_VAR: $(TF_ACCESS_KEY)
