# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: Terraform

jobs:
- job: job_1
  pool:
    vmImage: ubuntu-latest

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo let's see some magic $(TF_ACCESS_KEY)
    displayName: 'Run a multi-line script'
