# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: Terraform

stages:
  - stage: "terraform"
    jobs:
    - job: InstallTerraform
      pool:
        vmImage: ubuntu-latest

      steps:
      - task: TerraformTaskV4@0
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: 'latest'

      - bash: |
          export AWS_ACCESS_KEY_ID=$MY_TF_ACCESS_KEY
          export AWS_SECRET_ACCESS_KEY=$MY_TF_SECRET_KEY
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
        env:
          MY_TF_ACCESS_KEY: $(TF_ACCESS_KEY)
          MY_TF_SECRET_KEY: $(TF_SECRET_KEY)
